name: repos
namespace: repo_setup
version: 0.0.1
readme: README.md
authors:
  - Red Hat
description: TripleO Repos
build_ignore:
  - "*.egg-info"
  - .DS_Store
  - .eggs
  - .gitignore
  - .gitreview
  - .mypy_cache
  - .pytest_cache
  - .stestr
  - .stestr.conf
  - .tox
  - .vscode
  - MANIFEST.in
  - build
  - dist
  - doc
  - report.html
  - setup.cfg
  - setup.py
  - "tests/unit/*.*"
  - README.rst
  - tox.ini
  - repo_setup
  - zuul.d
  # excluded because galaxy server refuses uploads with __main___ inside
  - plugins/module_utils/repo_setup/get_hash/__main__.py
  - plugins/module_utils/repo_setup/yum_config/__main__.py
  # that is not needed for ansible modules and it would upset sanity (pylint)
  - plugins/module_utils/repo_setup/main.py

repository: https://github.com/ci-framework/repo-setup
license_file: LICENSE
