---
- name: Example usage for repo-setup-get-hash python module
  hosts: localhost
  tasks:
    - name: get component-ci-testing for victoria compute component
      repo_setup.repos.get_hash:
        os_version: centos8       # default: centos8
        release: victoria         # default: master
        component: compute        # default: None
        tag: component-ci-testing # default: current-podified
      register: component_ci_testing_victoria_compute

    - debug:
        msg: "Centos8 component-ci-testing victoria compute component: {{ component_ci_testing_victoria_compute['full_hash'] }}"

    - debug:
        var: component_ci_testing_victoria_compute

    - name: get centos9 podified-ci-testing for zed
      repo_setup.repos.get_hash:
        os_version: centos9
        release: zed
        tag: podified-ci-testing
      register: centos9_podified_ci_testing_zed

    - debug:
        msg: "Centos9 podified-ci-testing zed: {{ centos9_podified_ci_testing_zed['full_hash'] }}"

    - debug:
        var: centos9_repo_setup_ci_testing_zed

    - name: get current-podified centos9 for master branch
      repo_setup.repos.get_hash:
      register: centos9_current_repo_setup_master

    - debug:
        msg: "Centos9 current-podified master: {{ centos9_current_repo_setup_master['full_hash'] }}"

    - debug:
        var: centos9_current_repo_setup_master
